### DISCUSSION TITLE
import own module

### DISCUSSION THREAD

**Discussion by RandomCollection** [pawamoy/markdown-exec#62] [Q&A] [answered]
Hi,

I am trying to import and execute a self-written module using **markdown-exec**. It works perfectly well if **example.py** is restricted to standard packages but runs into **ModuleNotFoundError** errors when trying to import a self-written module. I have tried different specifications without success. Any advise is highly appreciated. Below the set-up:

I am using **Python 3.8** with the following repository

```
- package
   - docs
      - example.md
      - examples
         - example.py
   - src
      - module.py
```

with **example.md**:

~~~
```python exec="on" source="console"
--8<-- "docs/examples/example.py"
```
~~~

and **example.py**:

`from src.module import func`

and **module.py**:

```
def func():
   pass
```

with **mkdocs.yml**:

```
plugins:
- search
- markdown-exec
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_source: false 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      base_path: ["src", "."]
```

Kind regards and many thanks
