### ISSUE TITLE
[Feature] Option to globally disable execution 

### ISSUE THREAD

**Issue by eddiebergman** [pawamoy/markdown-exec#19]
**Is your feature request related to a problem? Please describe.**
For documentation with lots of executing example and live-reload, this can be a bit slow at times and no necessary while building non-code parts of the documentation. I'd like to turn it off while
focusing on the text and later enable it while working on code snippets.

**Describe the solution you'd like**
```yaml
plugins:
  - markdown-exec:
        enabled: !ENV [SOME_ENV_VAR, false]
```

This is similar to how the `offline` plugin works.

**Describe alternatives you've considered**
None really, I tried the above solution in case it was a nice global option that `mkdocs` provided but sadly it's not.

**Additional context**
I'd be happy to provide a PR with a little bit of guidance on:
* Where do options to a plugin get parsed, I'm unfamiliar with developing mkdocs plugins.
* What would be the least disruptive solution with a pointer or two.

**Comment by pawamoy** [comment]
Hey @eddiebergman, good idea! You can get inspiration from this PR: https://github.com/mkdocstrings/mkdocstrings/pull/504

**Comment by pawamoy** [comment]
MkDocs 1.6 adds an `enabled` setting to all plugins by default, so you can now do something like this:

```yaml
plugins:
- markdown-exec:
    enabled: !ENV [ENABLE_MARKDOWN_EXEC, false]
```
