### ISSUE TITLE
bug: source="tabbed-left" showing source vertically, rather than horizontally

### ISSUE THREAD

**Issue by MarcoGorelli** [pawamoy/markdown-exec#26]
### Description of the bug

Here is my output, when using `source="tabbed-left"`

![image](https://github.com/pawamoy/markdown-exec/assets/33491632/bf092036-06bb-47c7-8211-33f86c7e5d85)

### To Reproduce

```
mkdir mcve-mkdocs
cd mcve-mkdocs/
python3.11 -m venv .venv
. .venv/bin/activate
pip install mkdocs mkdocs markdown-exec[ansi]
mkdocs new .
```

Here's my `mkdocs.yml` file:
```yml
site_name: My Docs
markdown_extensions:
- pymdownx.tabbed
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
```

Here's my `docs/index.md` file:

````md
# Welcome to MkDocs

```python exec="true" source="tabbed-left"
print("I'm the result!")
```
````

### Expected behavior

From https://pawamoy.github.io/markdown-exec/usage/ , I was expecting the source and output to be side-by-side, like this:

![image](https://github.com/pawamoy/markdown-exec/assets/33491632/1b54e822-7292-490f-9071-cf854e165fe4)

### Environment information

```bash
python -m markdown_exec.debug  # | xclip -selection clipboard
```

- __System__: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- __Python__: cpython 3.11.6
- __Environment variables__:
- __Installed packages__:
  - `markdown-exec` v1.7.0

**Comment by pawamoy** [comment]
Looks like the theme you are using does not display the tabs as tabs. Which theme is it?

**Comment by MarcoGorelli** [comment]
thanks for your reply

I don't think I have a theme - I pasted my entire `mkdocs.yml` above, and then ran `mkdocs serve`

is there any theme you recommend using which is known to work?

**Comment by pawamoy** [comment]
Just tried locally and indeed the two built-in themes `mkdocs` and `readthedocs` do not seem to support tabs. The [`material`](https://squidfunk.github.io/mkdocs-material/) theme does.

**Comment by MarcoGorelli** [comment]
thanks, much appreciated

I must be doing something wrong, because I've tried the material theme but see:

![image](https://github.com/pawamoy/markdown-exec/assets/33491632/15fbb1b8-d8f1-49c6-99d7-68a9ba35c51e)

Here's what I've changed my `mkdocs.yml` file to:
```python
site_name: My Docs
theme:
    name: material
markdown_extensions:
- pymdownx.tabbed
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
```

`docs/index.md` is unchanged from my first post

**Comment by MarcoGorelli** [comment]
ooh, changing `mkdocs.yml` to
```yml
site_name: My Docs
theme:
    name: material
markdown_extensions:
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
```

and now it works as expected 🥳 , I get:

![image](https://github.com/pawamoy/markdown-exec/assets/33491632/29d8b6c1-8fdb-4ba5-89f9-a64bf73ed0ff)

**Comment by pawamoy** [comment]
Great, closing then :)

**Comment by pawamoy** [comment]
By the way, you can enable Markdown Exec as a plugin rather than a Markdown extension:

```yaml
plugins:
- markdown-exec
```

This will enable more features, especially ANSI colors support :)

**Comment by MarcoGorelli** [comment]
Thanks! I'm losing the syntax highlighting with that though

With
```yaml
site_name: My Docs
theme:
    name: material
markdown_extensions:
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
```
I get:
![image](https://github.com/pawamoy/markdown-exec/assets/33491632/a4329f54-34be-4f86-bd45-650476dfc635)


However, with
```yaml
site_name: My Docs
theme:
    name: material
plugins:
- search
- markdown-exec
markdown_extensions:
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
```

I get:

![image](https://github.com/pawamoy/markdown-exec/assets/33491632/6fe62cfa-4f11-4589-928b-030bf810d95c)
