### ISSUE TITLE
bug: can not run the example

### ISSUE THREAD

**Issue by elrandira** [pawamoy/markdown-exec#35]
### Description of the bug

I can not manage to get the example working

![image](https://github.com/pawamoy/markdown-exec/assets/82774041/d5dbdd4b-4a3f-4154-8c5e-4bfb72caa840)

### To Reproduce

- python -m venv markdown
- markdown\Scripts\activate.bat
- pip install mkdocs==1.3.1 markdown-exec==1.7.0
- mkdocs new test_mkexec
- cd test_mkexec
- add at the bottom of index.md

````md
```python exec="on"
print("Hello Markdown!")
```
````

- add in mkdocs.yml

```
plugins:
- search
- markdown-exec
```

- mkdocs serve

### Full traceback

INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.06 seconds
INFO     -  [17:25:07] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [17:25:07] Serving on http://127.0.0.1:8000/
INFO     -  [17:25:07] Browser connected: http://127.0.0.1:8000/

### Expected behavior

python code is interpreted and page show "hello world"

### Environment information

(markdown) C:\workplace\test>pip list
Package            Version
------------------ -------
click              8.1.7
colorama           0.4.6
ghp-import         2.1.0
importlib-metadata 7.0.1
Jinja2             3.1.3
Markdown           3.3.7
markdown-exec      1.7.0
MarkupSafe         2.1.4
mergedeep          1.3.4
mkdocs             1.3.1
packaging          23.2
pip                23.2.1
pymdown-extensions 10.4
python-dateutil    2.8.2
PyYAML             6.0.1
pyyaml_env_tag     0.1
setuptools         65.5.0
six                1.16.0
watchdog           3.0.0
zipp               3.17.0

(markdown) C:\workplace\test>python --version
Python 3.11.6

I tried with latest of mkdocs & markdown-exec without better result

What am I doing wrong?

**Comment by pawamoy** [comment]
I think the docs are unclear, sorry: you have to enable the `pymdownx.superfences` Markdown extension too.

**Comment by elrandira** [comment]
thank you, I had to add the following in the mkdocs.yml and it worked.

```
markdown_extensions:
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
```

**Comment by pawamoy** [comment]
You can just enable the extension without specific fences, the plugin will take care of adding them.

```yaml
plugins:
- search
- markdown-exec

markdown_extensions:
- pymdownx.superfences
```
